name: ci

on: [push, pull_request]

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/0.4.3/install.sh | sh

      - name: Set up python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev
        working-directory: ./server

      - name: Check format
        run: uv run black . --check --verbose
        working-directory: ./server
